http.host: "0.0.0.0"
xpack.monitoring.enabled: false

path.config: /usr/share/logstash/pipeline
path.logs: /var/log/logstash

pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

queue.type: memory
queue.max_bytes: 1024mb

log.level: info