spring:
  # datasource配置
  datasource:
    name: blog
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    username: root
    password: 43997K7k.

#  data:
#    redis:
#      password: 123456

  mail:
    host: smtp.qq.com
    port: 587
    username: 1448185924@qq.com
    password: czlrpanbmcerihga
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.qq.com
        debug: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liY8AiP9uI5DsZCR  # 你的 GitHub OAuth App client id
            client-secret: bef4b57011303aaa891724856954bc050b3d8c4a  # 你的 GitHub OAuth App client secret
            redirect-uri: http://47.94.57.175/auth/github/callback

aliyun:
  oss:
    endpoint: "oss-cn-beijing.aliyuncs.com"
    access-key-id: "LTAI5tSejtaTDzN3S2cpuWYh"
    access-key-secret: "nzdIdnvKrzgSq1dh31JNar0p3pJCgD"
    bucket-name: "hello-kitty-cat-sweet"

# 百度云内容审核配置
baidu:
  content:
    appId: "6620094" # 替换为你的 App ID
    apiKey: "tZvDGGlR83jubJsuksqnYObj" # 替换为你的 API Key
    secretKey: "7qZr8Y1lTzm6wEUteYU8u6W4KXKZkctL" # 替换为你的 Secret Key

jwt:
  secret: "gZYAaBzjFS6R6aLU9uTlIZb2vzsnxKv4KE38H2H6X3c="

encryption:
  key:
    pf46F20xY/x+owVHLxbSeA==

xunfei:
  appId: "c73dd22e"
  apiKey: "c09f43b355833ace9136ab3ed88d8723"
  apiSecret: "MWEwMTNkY2YyZjMzZDc0NWVkZTgyMTg3"
  patchId: "1905925166225440768"
  domain: "xdeepseekr1qwen7b"

tesseract:
  data:
    path: D:/program_25/tesseract/tessdata

