filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/blog/blog-api-metrics*.json
  json.keys_under_root: true
  json.add_error_key: true
  json.ignore_decoding_error: true
  json.message_key: message
  fields:
    app: blog-system
    environment: ${ENVIRONMENT:-dev}
    log_type: api-metrics
  fields_under_root: true
  multiline:
    pattern: '^{'
    negate: true
    match: after

- type: log
  enabled: true
  paths:
    - /var/log/blog/blog-error*.json
  json.keys_under_root: true
  json.add_error_key: true
  json.ignore_decoding_error: true
  json.message_key: log
  fields:
    app: blog-system
    environment: ${ENVIRONMENT:-dev}
    log_type: error
  fields_under_root: true
  multiline:
    pattern: '^{'
    negate: true
    match: after

- type: log
  enabled: true
  paths:
    - /var/log/blog/blog-system-metrics*.json
  json.keys_under_root: true
  json.add_error_key: true
  json.ignore_decoding_error: true
  json.message_key: log
  fields:
    app: blog-system
    environment: ${ENVIRONMENT:-dev}
    log_type: system-metrics
  fields_under_root: true
  multiline:
    pattern: '^{'
    negate: true
    match: after

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - timestamp:
      field: "@timestamp"
      layouts:
        - '2006-01-02T15:04:05.999Z'
        - '2006-01-02T15:04:05.999'
      test:
        - '2021-01-02T15:04:05.999Z'
        - '2021-01-02T15:04:05.999'
  - drop_fields:
      fields: ["agent", "ecs", "input", "log.offset"]

output.logstash:
  hosts: ["logstash:5000"]
  loadbalance: true
  worker: 2
  bulk_max_size: 2048
  compression_level: 3 # 添加压缩

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

setup.ilm.enabled: false
setup.template.enabled: false