filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/blog/blog-api-metrics-*.json
  json.keys_under_root: true
  json.add_error_key: true
  json.ignore_decoding_error: true
  fields:
    app: blog-system
    environment: ${ENVIRONMENT:-dev}
    log_type: api-metrics
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/blog/blog-error-*.json
  json.keys_under_root: true
  json.add_error_key: true
  json.ignore_decoding_error: true
  fields:
    app: blog-system
    environment: ${ENVIRONMENT:-dev}
    log_type: error
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/blog/blog-post-metrics-*.json
  json.keys_under_root: true
  json.add_error_key: true
  json.ignore_decoding_error: true
  fields:
    app: blog-system
    environment: ${ENVIRONMENT:-dev}
    log_type: post-metrics
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/blog/blog-system-metrics-*.json
  json.keys_under_root: true
  json.add_error_key: true
  json.ignore_decoding_error: true
  fields:
    app: blog-system
    environment: ${ENVIRONMENT:-dev}
    log_type: system-metrics
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/blog/blog-user-activity-*.json
  json.keys_under_root: true
  json.add_error_key: true
  json.ignore_decoding_error: true
  fields:
    app: blog-system
    environment: ${ENVIRONMENT:-dev}
    log_type: user-activity
  fields_under_root: true

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5000"]
  loadbalance: true
  bulk_max_size: 2048

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  rotateeverybytes: 10485760  # 10MB
  keepfiles: 7
  permissions: 0644

setup.ilm.enabled: false
setup.template.enabled: false